### ISSUE TITLE
IllegalLocationConstraintException for Wasabi-Storage

### ISSUE THREAD

**Issue by cloudmaker97** [peterrus/docker-s3-cron-backup#13]
> An error occurred (IllegalLocationConstraintException) when calling the CreateMultipartUpload operation: The EU location constraint is incompatible for the region specific endpoint this request was sent to.

The Region Endpoint is: `s3.eu-central-2.wasabisys.com` and the credentials are tested and valid.

```
backup:
  image: peterrus/s3-cron-backup
  environment:
    - AWS_ACCESS_KEY_ID=**** truncated *****
    - AWS_SECRET_ACCESS_KEY=**** truncated *****
    - S3_BUCKET_URL=s3://**** truncated *****/
    - AWS_DEFAULT_REGION=eu-central-2
    - S3_ENDPOINT_URL=https://s3.eu-central-2.wasabisys.com
    - CRON_SCHEDULE=0 */2 * * *
    - BACKUP_NAME=gitlab
  volumes:
    - /srv/gitlab:/data:ro
  restart: always
```
