### ISSUE TITLE
Data not getting mounted on S3

### ISSUE THREAD

**Issue by ghost** [peterrus/docker-s3-cron-backup#2]
I am a new bee to docker , please help me out with this
what path should I specify in volume: section
you say:
volumes:
      - /your/awesome/data:/data:ro
I am specifying 
volumes:
      - maildata:/var/mail

**Comment by peterrus** [comment]
/data is the path that is getting mounted inside the container, so that is the path that is going to be backup up to S3. If you have another service in the same docker-compose file that s3-cron-backup is defined in, you can use that volume like so:

```
maildata:/data:ro
```

If that doesn't make any sense, feel free to post your docker-compose file ;)

**Comment by ghost** [comment]
my-backup-unit:
    image: peterrus/s3-cron-backup
    environment:
      - AWS_ACCESS_KEY_ID=***
      - AWS_SECRET_ACCESS_KEY=***
      - S3_BUCKET_URL=**
      - AWS_DEFAULT_REGION=us-east-1
      - CRON_SCHEDULE=0 * * * * # run every hour
      - BACKUP_NAME=make-something-up
    volumes:
      - maildata:/var/mail:ro 
    restart: always

I am using this configuration ,when i run the docket a tar file gets created in our S3 bucket but it's empty i mean there are no files inside tar

**Comment by peterrus** [comment]
maildata should be a volume that is defined somewhere else in the
docker-compose file.

See here for an example:

https://stackoverflow.com/a/44284993

Also you should change /var/mail back to /data as /data is a folder inside
the backupcontainers filesystem that gets backed up to S3.

If the service you are trying to backup is just a regular directory on your
docker host you can mount it inside the backupcontainer using the following
syntax: /var/mail:/data:ro.

Either way the right part (after the first ':' should always be '/data' or
else the backup will simply upload an empty archive).

Let me know how it goes ;)

**Comment by ghost** [comment]
i m using following configuration

```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: domain.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE

  my-backup-unit:
    image: peterrus/s3-cron-backup
    environment:
      - AWS_ACCESS_KEY_ID=***
      - AWS_SECRET_ACCESS_KEY=***
      - S3_BUCKET_URL=**
       - AWS_DEFAULT_REGION=us-east-1
      - CRON_SCHEDULE=0 * * * * # run every hour
      - BACKUP_NAME=make-something-up
volumes:
    - maildata:/data:ro [NOT Working]
restart: always
volumes:
  maildata:
      driver: local
  mailstate:
      driver: local
```

what should i specify insted of  - maildata:/data:ro  ???
